//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misa_MF736_HqMinh_Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Misa_MF736_HqMinh_Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới thành công.
        /// </summary>
        public static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khoản thu bị trùng, vui lòng kiểm tra lại..
        /// </summary>
        public static string ErroService_DuplicateFeeName {
            get {
                return ResourceManager.GetString("ErroService_DuplicateFeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phạm vi thu không được để trống, vui lòng kiểm tra lại..
        /// </summary>
        public static string ErroService_EmptyFeeApplyObject {
            get {
                return ResourceManager.GetString("ErroService_EmptyFeeApplyObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khoản thu không được để trống, vui lòng kiểm tra lại..
        /// </summary>
        public static string ErroService_EmptyFeeName {
            get {
                return ResourceManager.GetString("ErroService_EmptyFeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kì thu không được để trống, vui lòng kiểm tra lại..
        /// </summary>
        public static string ErroService_EmptyFeePeriod {
            get {
                return ResourceManager.GetString("ErroService_EmptyFeePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mức thu không được để trống, vui lòng kiểm tra lại..
        /// </summary>
        public static string ErroService_EmptyFeePrice {
            get {
                return ResourceManager.GetString("ErroService_EmptyFeePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính không được để trống, vui lòng kiểm tra lại..
        /// </summary>
        public static string ErroService_EmptyFeeUnit {
            get {
                return ResourceManager.GetString("ErroService_EmptyFeeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ để được trợ giúp.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa thành công.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
    }
}
